name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Run Unit Tests
      run: go test -v ./...

  docker-build:
    needs: test # This ensures we only build Docker if tests pass
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t cicd-demo:latest .
      
    - name: Verify Docker Image
      run: docker image inspect cicd-demo:latest > /dev/null
